### PR TITLE
#35, 36 + other Bug fixs + Battery, Books, Electonics, Glassworking, Industrials, Rings, Smithing Description updates.

### PR DESCRIPTION
**Pull request by Yell420**

### CODE REVIEW

**Review by Yell420 — COMMENTED** [review]
looks good

**Review by Yell420 — COMMENTED** [review]
Reviewed all 3, looks to be correct, May need to adjust recipes to specific materials in books.txt in the future - it looks like this was underway and was stopped.

**Review by Yell420 — COMMENTED** [review]
reviewed

**Review by Yell420 — COMMENTED** [review]
Confirmed changes with books and rings.txt

**Review by Yell420 — COMMENTED** [review]
This updates Books.txt, industrial, smithing, rings.txt(jewlcrafting and Electonics with better descriptions instead of generic "Make Item"

**Review by Yell420 — COMMENTED** [review]
#36 Bug fix + Battery, Books, Electonics, Glassworking, Industrials, Rings, Smithing Update.

**Review by Yell420 — COMMENTED** [review]
renames HCCatwhitemale to HCCatwmale bug resolution by #35 [lanceris](https://github.com/lanceris)

**Comment by Yell420** [comment]
Changes werw confirmed in-game on test server loaded with 200+ mods.

**Review by robotex140 — APPROVED** [review]

**Pull request merged**
